# Generated by Django 5.1.4 on 2025-01-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
