# Generated by Django 5.1.4 on 2025-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_tracker_api', '0002_trip_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='times_visited',
        ),
        migrations.AddField(
            model_name='trip',
            name='date_visited',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
