# Generated by Django 4.2.17 on 2025-01-10 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('park_tracker_api', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='times_visited',
        ),
        migrations.AddField(
            model_name='trip',
            name='date_visited',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
