# Generated by Django 4.2.17 on 2025-01-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park_tracker_api', '0004_remove_trip_times_visited_trip_date_visited'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usermodel',
        ),
    ]
